const assert = require('node:assert/strict');
const { distance, parseFeed, filterEvents } = require('../core.js');
const now = 1800000000000;
assert.equal(distance({ lat: 0, lon: 0 }, { lat: 0, lon: 0 }), 0);
assert.ok(Math.abs(distance({ lat: 0, lon: 0 }, { lat: 0, lon: 1 }) - 111.195) < 0.01);
assert.ok(distance({ lat: 0, lon: 179.9 }, { lat: 0, lon: -179.9 }) < 23, 'antimeridian uses shortest distance');
assert.ok(Number.isFinite(distance({ lat: 90, lon: 0 }, { lat: -90, lon: 180 })), 'antipodes are finite');
const feature = (id, lon, mag, age, type = 'earthquake') => ({ id, properties: { mag, time: now - age * 3600000, place: 'Test', type }, geometry: { coordinates: [lon, 0, 10] } });
const data = { type: 'FeatureCollection', features: [feature('near', 0.1, 2, 1), feature('far', 20, 5, 2), feature('old', 0, 7, 100), feature('unknown', 1, null, 3), feature('negative', 0, -2, 0.1), feature('future', 0, 6, -1), feature('blast', 0, 6, 1, 'quarry blast'), feature('bad', 999, 6, 1)] };
const events = parseFeed(data);
assert.equal(events.length, 6);
const base = { now, hours: 24, mag: -1, reference: null, radius: Infinity, sort: 'time' };
assert.deepEqual(filterEvents(events, base).map(e => e.id), ['negative', 'near', 'far', 'unknown']);
assert.deepEqual(filterEvents(events, { ...base, mag: 3 }).map(e => e.id), ['far']);
assert.deepEqual(filterEvents(events, { ...base, reference: { lat: 0, lon: 0 }, radius: 100, sort: 'distance' }).map(e => e.id), ['negative', 'near']);
assert.equal(filterEvents(events, { ...base, sort: 'magnitude' }).at(-1).id, 'unknown');
assert.equal(filterEvents(events, { ...base, hours: 168 }).length, 5);
assert.throws(() => parseFeed({ features: [] }));
assert.equal(events[0].distance, undefined, 'no mutation of source data');
console.log('PASS: distance, dateline, poles, invalid feed, event types, missing/negative magnitudes, time, distance and sorting.');
